---
sudo: true
dist: trusty
language: ruby
cache: bundler
install:
  - wget https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb
  - sudo dpkg -i puppetlabs-release-pc1-trusty.deb
  - sudo apt-get update
  - sudo apt-get install pdk
script:
  - 'pdk $CHECK'
rvm:
  - 2.4.3
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="validate --debug"
    -
      env: CHECK="test unit --debug"
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
